Skia support Third party Fast Image component
nagra-opentv/react-native-fast-image pull request #3
Opened 2023-01-03 10:40 UTC by ddesai96

Skia supported third-party components.
1. All codes are duplicated as an image component.
2. while inheriting the image components to fast image components, getting memory-related issues, all codes are kept as duplicates.
3. In the fast image, shadow node, props, and event emitter codes are generated from codegen.

2023-01-05 12:15 UTC, pprabhu-ng commented on skia/BUILD.gn
> +    "RSkComponentProviderFastImage.cpp",
should the file be RSk or RS for thirdparty ?

2023-01-05 12:16 UTC, pprabhu-ng commented on skia/BUILD.gn
> +  sources += [
is this empty sources required to be defined ?

2023-01-05 12:17 UTC, pprabhu-ng commented on skia/RSkComponentFastImage.cpp
> +* Copyright (C) Kudo Chien
Kudo copyright not required

2023-01-06 06:52 UTC, pprabhu-ng commented on skia/RSkComponentFastImage.cpp
> +  This can be avoided buy inheritance . But when we did so faced
typo erro 
buy -> by

2023-01-06 06:52 UTC, pprabhu-ng commented on skia/RSkComponentFastImageView.cpp
> +  This can be avoided buy inheritance . But when we did so faced
typo here ?
buy -> by

2023-01-06 06:52 UTC, pprabhu-ng commented on skia/RSkComponentFastImageView.cpp
> +    } else if((imageProps.source.uri.substr(0, 7) == "http://") || (imageProps.source.uri.substr(0, 8) == "https://")) {
can this logic be a inline function ?
because same check is again done at line 105

2023-01-06 06:52 UTC, pprabhu-ng commented on skia/RSkComponentFastImageView.cpp
> +   FastImageViewEventEmitter::OnFastImageLoad ImageLoadsize;
variable name to start with lowercase

2023-01-06 06:52 UTC, pprabhu-ng commented on skia/RSkComponentFastImageView.cpp
> +   imageEventEmitter_->onFastImageLoadEnd(imageLoad);
can we directly create the object during the call itself  something like below for optimisation
onFastImageError(FastImageViewEventEmitter::OnFastImageError{})

comment applicable for all other places of event emitter usage

2023-01-06 06:52 UTC, pprabhu-ng commented on skia/RSkComponentFastImageView.cpp
> +   imageEventEmitter_->onFastImageLoad(ImageLoadsize);
ios is sending image size for this event .. but we are sending image frame size. can you confirm if the value sent is proper.

2023-01-06 06:52 UTC, pprabhu-ng commented on skia/RSkComponentFastImageView.h
> +  sk_sp<SkImage> networkImageData_;
do we need the same variables as defined in Image class.
If we require , can we use diff name to avoid confusion

2023-01-06 06:52 UTC, pprabhu-ng commented on skia/react/renderer/components/rnfastimage/Props.cpp
> +         RNS_LOG_INFO(__func__);
is this print valid ?

2023-01-08 18:19 UTC, munezbn approved these changes

2023-01-09 16:42 UTC, pprabhu-ng commented on skia/BUILD.gn
> +                  "//react-native/",
should these be deps instead of include_dir ?

2023-01-09 16:44 UTC, pprabhu-ng commented on skia/RSkComponentFastImageView.h
> +    SkColor tintColor;
is the indentation proper here ?

2023-01-09 16:45 UTC, pprabhu-ng commented on skia/RSkComponentFastImageView.h
> +  std::shared_ptr<FastImageViewEventEmitter const> imageEventEmitter_;
can this be named as fastimageEventEmitter ?

2023-01-09 16:46 UTC, pprabhu-ng commented on skia/react/renderer/components/rnfastimage/Props.h
> +  RNS_LOG_INFO(__func__ << ":" << __LINE__ );
cleanup of RNS_LOG_INFO required in this file

2023-01-10 11:54 UTC, ddesai96 commented on skia/RSkComponentFastImageView.h
> +    SkColor tintColor;
yes

2023-01-10 13:17 UTC, munezbn approved these changes

2023-01-11 05:11 UTC, pprabhu-ng approved these changes

2023-01-11 09:33 UTC, chatrapathi06 requested changes

2023-01-11 09:33 UTC, chatrapathi06 commented on skia/BUILD.gn
> +  # RNS Fabric Component and its dependencies
added header files

2023-01-11 09:33 UTC, chatrapathi06 commented on skia/RSkComponentFastImageView.cpp
> +    networkFastImageData_ = nullptr;
move to updateprops

2023-01-11 09:33 UTC, chatrapathi06 commented on skia/RSkComponentFastImageView.h
> + protected:
remove protector

2023-01-11 10:30 UTC, chatrapathi06 approved these changes

2023-01-11 10:30 UTC, shefayaparwin approved these changes

2023-01-11 12:11 UTC, merged